<?php

/**
 * @file
 * SPECBEE Date Time Location module.
 */

 /**
  * Implements hook_theme().
  */
function specbee_date_location_theme($existing, $type, $theme, $path) {
    return [
        'specbee_date_location__datetimelocation_block' => [
            'variables' => [
                'country' => NULL,
                'city' => NULL,
                'date' => NULL,
                'time' => NULL,
            ]
        ],
    ];
}